app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.master),  #the path for our index view
    path('shop', views.shop),
    path('product-details/<str:id>', views.productDetails),
    path('checkout', views.checkout),
    path('user-login', views.login),
    path('user-register', views.register),
    path('user-logout', views.logoutUser),
    path('account', views.account),
    path('store-profile', views.storeUserProfile,name='storeprofile'),
    path('wishlist', views.wishlist),
    path('cart', views.cart,name='cart'),
    path('order',views.order,name='ordernow'),
    path('search',views.search,name='search'),
    
    
    path('contact', views.contact),
    path('blogs', views.blogs),
    path('blog-single', views.singleblog),
    path('user-profile/<str:id>',views.profile),
    path('edit-profile/<str:id>',views.profileSetting),
    
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),

]

leaseattire/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
] 

app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=150)
    
    def __str__(self):
            return self.name
    
class Sub_Category(models.Model):
    name =models.CharField(max_length=150)
    category =models.ForeignKey(Category, on_delete=models.CASCADE)  
      
    def __str__(self):
            return self.name
     
class Brand(models.Model):
    name=models.CharField(max_length=150)   
    def __str__(self):
            return self.name

class Product(models.Model):
    name =models.CharField(max_length=150)
    price=models.IntegerField()
    rentalprice=models.IntegerField()
    image =models.ImageField(upload_to='static/productImg')
    date =models.DateField(auto_now_add=True)
    category =models.ForeignKey(Category, on_delete=models.CASCADE,default=None)  
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE, default=None) 
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, default=None) 
    
    def __str__(self):
            return self.name
    
class Banner(models.Model):
     heading=models.CharField(max_length=200)
     sub_heading=models.CharField(max_length=200)
     short_description=models.TextField()
     image=models.ImageField(upload_to='static/bannerImg')
     def __str__(self):
            return self.heading 
             
class Profile(models.Model):
      user = models.OneToOneField(User, on_delete=models.CASCADE )
      fullname =models.CharField(max_length=150)
      nickname =models.CharField(max_length=150)
      phone_number =models.CharField(max_length=10)
      second_number =models.CharField(max_length=10)
      disctrict =models.CharField(max_length=150)
      city =models.CharField(max_length=150)
      local_area =models.CharField(max_length=150)
      house_number =models.CharField(max_length=150)
      birthday =models.DateField( help_text = "User birthdate")
      gender =models.CharField(max_length=150)
      profile_picture =models.ImageField(upload_to='static/profileImage')
      
      def __str__(self):
            return self.fullname 
      
      def age(self):
        import datetime
        return int((datetime.date.today() - self.birthday).days / 365.25  )
    
    
STATUS_CHOICES = [
('Pending', 'Pending'),
('Accept', 'Accept'),
('Deliver', 'Deliver'),
('Sucess', 'Sucess'),
]
class Order(models.Model):
    image = models. ImageField(upload_to='static/order/image')
    product = models.CharField(max_length=1000,default='')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.CharField(max_length=10)
    total = models.CharField(max_length=1000,default='')  
    address = models.TextField()
    phone = models.CharField(max_length=18)
    start_date = models.DateField(help_text = "Start rental date")
    end_date = models.DateField(help_text = "End rental date")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    note = models.TextField()     

templates/blog.html
{% extends 'master.html' %} {% block title %}Blog{% endblock %} {% block body%}

<section>
  <div class="container">
    <div class="row">
        <div class="col-sm-3">
          <div class="left-sidebar">
            <h2>Category</h2>
            <div class="panel-group category-products" id="accordian">
              <!--category-productsr-->
  
              {% for cat in category %}
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordian"  href="#{{cat.id}}" >
                      <span class="badge pull-right">
                        <i class="fa fa-plus"></i>
                      </span>
                      {{cat.name}}
                    </a>
                  </h4>
                </div>
                <div id="{{cat.id}}" class="panel-collapse collapse">
                  <div class="panel-body">
                    {% for subcat in cat.sub_category_set.all %}
                    <ul>
                      <li><a href="/?category={{subcat.id}}">{{subcat.name}} </a></li>
                        </ul>
                    {% endfor %}
                  </div>
                </div>
              </div>
            
              {% endfor %}
             
            </div>
          </div>
        </div>
      <div class="col-sm-9">
        <div class="blog-post-area">
          <h2 class="title text-center">Latest From our Blog</h2>
          <div class="single-blog-post">
            <h3>Girls Pink T Shirt arrived in store</h3>
            <div class="post-meta">
              <ul>
                <li><i class="fa fa-user"></i> Mac Doe</li>
                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
              </ul>
              <span>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
              </span>
            </div>
            <a href="">
              <img src="images/blog/blog-one.jpg" alt="" />
            </a>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur.
            </p>
            <a class="btn btn-primary" href="">Read More</a>
          </div>
          <div class="single-blog-post">
            <h3>Girls Pink T Shirt arrived in store</h3>
            <div class="post-meta">
              <ul>
                <li><i class="fa fa-user"></i> Mac Doe</li>
                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
              </ul>
              <span>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
              </span>
            </div>
            <a href="">
              <img src="images/blog/blog-two.jpg" alt="" />
            </a>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur.
            </p>
            <a class="btn btn-primary" href="">Read More</a>
          </div>
          <div class="single-blog-post">
            <h3>Girls Pink T Shirt arrived in store</h3>
            <div class="post-meta">
              <ul>
                <li><i class="fa fa-user"></i> Mac Doe</li>
                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
              </ul>
              <span>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
              </span>
            </div>
            <a href="">
              <img src="images/blog/blog-three.jpg" alt="" />
            </a>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur.
            </p>
            <a class="btn btn-primary" href="">Read More</a>
          </div>
          <div class="pagination-area">
            <ul class="pagination">
              <li><a href="" class="active">1</a></li>
              <li><a href="">2</a></li>
              <li><a href="">3</a></li>
              <li>
                <a href=""><i class="fa fa-angle-double-right"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/cart.html
{% extends 'master.html' %}
 {% block title %}Cart{% endblock %} 
 {% block body%}
{% load cart_tag %}
<section id="cart_items">
  <div class="container">
    <div class="breadcrumbs">
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li class="active">Shopping Cart</li>
      </ol>
    </div>
    
    <div class="table-responsive cart_info">
      <table class="table table-condensed">
        <thead>
          <tr class="cart_menu">
            <td class="image">Item</td>
            <td class="description"></td>
            <td class="price">Price</td>
            <td class="quantity">Days</td>
            <td class="total">Total</td>
            <td></td>
          </tr>
        </thead>

        <tbody>
          {% for key,value in request.session.cart.items %}
          <tr>
            <td class="cart_product">
              <a href=""><img src="{{value.image}}" width="120" height="80" alt="" /></a>
            </td>
            <td class="cart_description">
              <h4><a href="">{{value.name}}</a></h4>
              <p>{{value.brand}}</p>
            </td>
            <td class="cart_price">
              <p>{{value.price}}</p>
            </td>
            <td class="cart_quantity">
              <div class="cart_quantity_button">
                <a class="cart_quantity_up" href="{% url 'item_increment' value.product_id %}"> + </a>
                <input
                  class="cart_quantity_input"
                  type="text"
                  name="quantity"
                  value=" {{value.quantity}}"
                  autocomplete="off"
                  size="2"
                />
                <a class="cart_quantity_down" href="{% url 'item_decrement' value.product_id %}"> - </a>
              </div>
            </td>
            <td class="cart_total">
              <p class="cart_total_price">{{ value.price|multiply:value.quantity }}</p>
            </td>
            <td class="cart_delete">
              <a class="cart_quantity_delete" href="{% url 'item_clear' value.product_id %}"
                ><i class="fa fa-times"></i
              ></a>
            </td>
          </tr>
          
          {% endfor %}
         
        </tbody>
      </table>
       {% if request.session.cart|length == 0 %}
          <p>No any Item Added to cart </p>
          {% endif %}

          
    </div>
  </div>
</section>
<!--/#cart_items-->





<section id="do_action">
  <div class="container">
    <div class="heading">
      <h3>What would you like to do next?</h3>
      <p>
       Now its time for check out or
       if you want to change the product or number of day please do befor checkout..
      </p>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="total_area">
          <ul>
            <li>Cart Sub Total <span>{{ cart_total_amount }}</span></li>
            <li>Shipping Cost <span>Free</span></li>
            <li>Total <span> {{ cart_total_amount }}</span></li>
          </ul>
          
           <a class="btn btn-default check_out" data-toggle="modal" data-target="#exampleModalCenter">Rent Now </a>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Please Fill the information for order</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
          <div class="modal-body">
          <form action="{% url 'ordernow' %}" method="POST" >
            {% csrf_token %}
              <div class="form-group">
                <label for="exampleInputEmail1">Start Date</label>
                <input type="date" name="start_date" class="form-control" >
                </div>
              
              <div class="form-group">
               <label for="exampleInputEmail1">Shipping Address</label>
                <input type="text" name="address" placeholder="Enter Your full shipping address" class="form-control" >
              </div>
              
              <div class="form-group">
               <label for="exampleInputEmail1">Phone Number</label>
                <input type="number" name="phone" placeholder="Enter Your phone number" class="form-control" >
              </div>
              
              <div class="form-group">
               <label for="exampleInputEmail1">Any Note</label>
                <textarea name="note" class="form-control" > </textarea>
              </div>
              
               
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>

          </div>
      </div>
  </div>
</div>

{% endblock %}

templates/index.html
{% extends 'master.html' %}
 {% block title %}Home{% endblock %}
  {% block body %}

<section id="slider">
  <!--slider-->
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div id="slider-carousel" class="carousel slide" data-ride="carousel">
         
         
         
          <div class="carousel-inner">
           
           {% for b in banner %}
            {% if forloop.counter == 1 %}
              <div class="item active">
              {% else %}
              <div class="item">
              {% endif %}   
    
           <div class="col-sm-6">
                <h1><span>{{b.heading}}</span></h1>
                <h2>{{b.sub_heading}}</h2>
                <p>
                  {{b.short_description}}
                </p>
                <button type="button" class="btn btn-default get">
                  Get it now
                </button>
              </div>
              <div class="col-sm-6">
                <img
                  src="{{b.image}}"
                  class="girl img-responsive"
                  alt="" style='height:400px;'
                />
                {% comment %} <img src="static/images/home/pricing.png" class="pricing" alt="" /> {% endcomment %}
              </div>
            </div>
        {% endfor %}
          </div>

          <a
            href="#slider-carousel"
            class="left control-carousel hidden-xs"
            data-slide="prev"
          >
            <i class="fa fa-angle-left"></i>
          </a>
          <a
            href="#slider-carousel"
            class="right control-carousel hidden-xs"
            data-slide="next"
          >
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--/slider-->

<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <h2>Category</h2>
          <div class="panel-group category-products" id="accordian">
            <!--category-productsr-->

            {% for cat in category %}
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordian"  href="#{{cat.id}}" >
                    <span class="badge pull-right">
                      <i class="fa fa-plus"></i>
                    </span>
                    {{cat.name}}
                  </a>
                </h4>
              </div>
              <div id="{{cat.id}}" class="panel-collapse collapse">
                <div class="panel-body">
                  {% for subcat in cat.sub_category_set.all %}
                  <ul>
                    <li><a href="/?category={{subcat.id}}">{{subcat.name}} </a></li>
                      </ul>
                  {% endfor %}
                </div>
              </div>
            </div>
          
            {% endfor %}
           
          </div>
          <!--/category-products-->

          <div class="brands_products">
            <!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
              <ul class="nav nav-pills nav-stacked">
               {% for b in brand %}
                <li>
                  <a href="/?brand={{b.id}}"> <span class="pull-right">( )</span>{{b.name}}</a>
                </li>
               {% endfor %}
              </ul>
            </div>
          </div>
          <!--/brands_products-->

          <div class="price-range">
            <!--price-range-->
            <h2>Price Range</h2>
            <div class="well text-center">
              <input
                type="text"
                class="span2"
                value=""
                data-slider-min="0"
                data-slider-max="600"
                data-slider-step="5"
                data-slider-value="[250,450]"
                id="sl2"
              /><br />
              <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
            </div>
          </div>
          <!--/price-range-->

          <div class="shipping text-center">
            <!--shipping-->
            <img src="images/home/shipping.jpg" alt="" />
          </div>
          <!--/shipping-->
        </div>
      </div>

      <div class="col-sm-9 padding-right">
        <div class="features_items">
          <!--features_items-->
          <h2 class="title text-center">Features Items</h2>
       
       {% for p in product %}
          <div class="col-sm-4">
            <div class="product-image-wrapper">
              <div class="single-products">
                <div class="productinfo text-center">
                  <img src="{{p.image}}" alt=""  style='height:300px;width:300px;'/>
                  <h2>Rent at Rs.{{p.price}}</h2>
                  <p>{{p.name}}</p>
                  <a href="{% url 'cart_add' p.id %}" class="btn btn-default add-to-cart"
                    ><i class="fa fa-shopping-cart"></i>Add to cart</a
                  >
                </div>
                <div class="product-overlay">
                  <div class="overlay-content">
                    <h2>Actual Price Rs{{p.rentalprice}}</h2>
                    <p>{{p.brand}}</p>
                    <a href="product-details/{{p.id}}" class="btn btn-default add-to-cart"
                      >View More</a
                    >
                  </div>
                </div>
              </div>
              <div class="choose">
                <ul class="nav nav-pills nav-justified">
                  <li>
                    <a href="#"
                      ><i class="fa fa-plus-square"></i>Add to wishlist</a
                    >
                  </li>
                  <li>
                    <a href="#"
                      ><i class="fa fa-plus-square"></i>Add to compare</a
                    >
                  </li>
                </ul>
              </div>
            </div>
          </div>
       {% endfor %}
      </div>
        <!--features_items-->

        <div class="category-tab">
          <!--category-tab-->
          <div class="col-sm-12">
            <ul class="nav nav-tabs">
              {% for sub in subcategory %}
                {% if forloop.counter == 1 %}
              <li class="active">
              {% else %}
              <li >
              {% endif %}   
                 <a href="#{{sub.id}}" data-toggle="tab">
                  {{sub.name}}
                </a>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="tab-content">
            <div class="tab-pane fade active in" id="{{sub.id}}">
             {% for p in subproduct%}
              <div class="col-sm-3">
                <div class="product-image-wrapper">
                  <div class="single-products">
                    <div class="productinfo text-center">
                      <img src="{{p.image.url}}" style="height:250px;" alt="" />
                      <h2>{{p.rentalprice}}</h2>
                      <p>{{p.name}}</p>
                      <a href="#" class="btn btn-default add-to-cart"
                        ><i class="fa fa-shopping-cart"></i>Add to cart</a
                      >
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}

            </div>

           
          </div>
        </div>
        <!--/category-tab-->

        <div class="recommended_items">
          <!--recommended_items-->
          <h2 class="title text-center">recommended items</h2>

          <div
            id="recommended-item-carousel"
            class="carousel slide"
            data-ride="carousel"
          >
          <div class="carousel-inner">
            {% for p in product %}
              {% if forloop.counter == 1 %}
              <div class="item active">
                {% else %}
                <div class="item">
                  {% endif %}   
                  
                <div class="col-sm-4">
                  <div class="product-image-wrapper">
                    <div class="single-products">
                      <div class="productinfo text-center">
                        <img src="{{p.image}}" style="height:250px;" alt="" />
                        <h2>{{p.rentalprice}}</h2>
                        <p>{{p.name}}</p>
                        <a href="#" class="btn btn-default add-to-cart"
                          ><i class="fa fa-shopping-cart"></i>Add to cart</a
                        >
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
             
            </div>
            <a
              class="left recommended-item-control"
              href="#recommended-item-carousel"
              data-slide="prev"
            >
              <i class="fa fa-angle-left"></i>
            </a>
            <a
              class="right recommended-item-control"
              href="#recommended-item-carousel"
              data-slide="next"
            >
              <i class="fa fa-angle-right"></i>
            </a>
          </div>
        </div>
        <!--/recommended_items-->
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/login.html
{% extends 'master.html' %} 
{% block title %}Login{% endblock %}
{% load static
{% block body%}
<section id="form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-4 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<h2>Login to your account</h2>
						<form action="" method="POST" >
							{% csrf_token %}
							<input type="text" name="user" placeholder="Enter UserName" />
							<input type="password" name="password" placeholder="Enter Password" />
							<span>
								<input type="checkbox" class="checkbox"> 
								Remember Me ?  
                			 <a href="user-register">Register</a>
							</span>
              
             
							<button type="submit" class="btn btn-default">Login</button>
						</form>
					</div><!--/login form-->
				</div>
				<div class="col-sm-1">
					<h2 class="or">OR</h2>
				</div>
				<div class="col-sm-4">
	       <img src="static/images/social.png" alt=""  style="height:250px;" />
     
			</div>
		</div>
	</section><!--/form-->





{% endblock %}

templates/shop.html
{% extends 'master.html' %} {% block title %}Shop{% endblock %} {% block body %}
<section id="advertisement">
  <div class="container">
    <img src="images/shop/advertisement.jpg" alt="" />
  </div>
</section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <h2>Category</h2>
          <div class="panel-group category-products" id="accordian">
            <!--category-productsr-->

            {% for cat in category %}
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordian"  href="#{{cat.id}}" >
                    <span class="badge pull-right">
                      <i class="fa fa-plus"></i>
                    </span>
                    {{cat.name}}
                  </a>
                </h4>
              </div>
              <div id="{{cat.id}}" class="panel-collapse collapse">
                <div class="panel-body">
                  {% for subcat in cat.sub_category_set.all %}
                  <ul>
                    <li><a href="/?category={{subcat.id}}">{{subcat.name}} </a></li>
                      </ul>
                  {% endfor %}
                </div>
              </div>
            </div>
          
            {% endfor %}
           
          </div>
          <!--/category-products-->

          <div class="brands_products">
            <!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
              <ul class="nav nav-pills nav-stacked">
               {% for b in brand %}
                <li>
                  <a href="/?brand={{b.id}}"> <span class="pull-right">( )</span>{{b.name}}</a>
                </li>
               {% endfor %}
              </ul>
            </div>
          </div>
          <!--/brands_products-->

          <div class="price-range">
            <!--price-range-->
            <h2>Price Range</h2>
            <div class="well text-center">
              <input
                type="text"
                class="span2"
                value=""
                data-slider-min="0"
                data-slider-max="600"
                data-slider-step="5"
                data-slider-value="[250,450]"
                id="sl2"
              /><br />
              <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
            </div>
          </div>
          <!--/price-range-->

          <div class="shipping text-center">
            <!--shipping-->
            <img src="images/home/shipping.jpg" alt="" />
          </div>
          <!--/shipping-->
        </div>
      </div>

      <div class="col-sm-9 padding-right">
        <div class="features_items">
          <!--features_items-->
          <h2 class="title text-center">Features Items</h2>
          
           {% for p in product %}
          <div class="col-sm-4">
            <div class="product-image-wrapper">
              <div class="single-products">
                <div class="productinfo text-center">
                  <img src="{{p.image}}" alt=""  style='height:300px;width:300px;'/>
                  <h2>Rent at Rs.{{p.rentalprice}}</h2>
                  <p>{{p.name}}</p>
                  <a href="#" class="btn btn-default add-to-cart"
                    ><i class="fa fa-shopping-cart"></i>Add to cart</a
                  >
                </div>
                <div class="product-overlay">
                  <div class="overlay-content">
                    <h2>Actual Price Rs{{p.price}}</h2>
                    <p>{{p.brand}}</p>
                    <a href="product-details/{{p.id}}" class="btn btn-default add-to-cart"
                      >View More</a
                    >
                  </div>
                </div>
              </div>
              <div class="choose">
                <ul class="nav nav-pills nav-justified">
                  <li>
                    <a href="#"
                      ><i class="fa fa-plus-square"></i>Add to wishlist</a
                    >
                  </li>
                  <li>
                    <a href="#"
                      ><i class="fa fa-plus-square"></i>Add to compare</a
                    >
                  </li>
                </ul>
              </div>
            </div>
          </div>
       {% endfor %}
     
          
          
      
         
          <ul class="pagination">
            <li class="active"><a href="">1</a></li>
            <li><a href="">2</a></li>
            <li><a href="">3</a></li>
            <li><a href="">&raquo;</a></li>
          </ul>
        </div>
        <!--features_items-->
      </div>
    </div>
  </div>
</section>

{% endblock body %}